GET http://localhost:8080/proper/extract/トランプ大統領が来日しました。

###

GET http://localhost:8080/proper/count/左側のタブがリクエスト、右側のタブがレスポンスです。ブラウザの拡張機能を使うでもなく、ターミナルでたたくでもなく、スタンドアローンなソフトを使うでもなく、エディタ上でリクエスト・レスポンスが完結してしまいます。しかも、使い方さえ知れば色々な形式のリクエストをテストしたり、設定を読み込んだりできます。使い方

###
POST http://localhost:8080/proper/count
Content-Type: application/json

{
    "text": "ツイッター上には、熱海市伊豆山の土石流の様子を撮影したとみられる映像や写真が複数、投稿されています。映像の1つでは、斜面をすごい勢いで大量の土砂の混じった水が流れてきて、複数の住宅を飲み込んでいく様子が確認できます。住宅はバラバラになって流されていき、傾いた電信柱から火花が出る様子も確認できます。現場には消防車のほか消防隊員と見られる姿も確認でき、走って逃げる様子も映されています。"
}

###
POST http://localhost:8080/proper/count
Content-Type: application/json

{
    "text": "神奈川県平塚市は市内を流れる金目川に加えて、その支流の鈴川、河内川、大根川、座禅川、板戸川でも氾濫が発生している可能性があるとして流域の住民を対象に「緊急安全確保」を出しました。警戒レベルで最も高いレベル5で、近くの建物や自宅の2階以上、斜面から離れた場所など周囲の状況を確認し、少しでも安全な場所で命が助かる可能性の高い行動を取るよう呼びかけています。"
}
